@startuml

' Definir los componentes
component Token
component FileReader
component Providers
component AST

package "Lexer, Parser e Interpreter" {
    component Lexer {
    }

    component Parser {
        [Parser] --> AST
    }

    component Interpreter {
        [Interpreter] --> AST
    }
}

package "Linter y Formatter" {
    component Formatter {
    }

    component Linter {
    }
}

package "Runner y CLI" {
    component Runner {
        [Runner] -down-> Token
        [Runner] -down-> AST
        [Runner] --> "Lexer, Parser e Interpreter"
        [Runner] -up-> "Linter y Formatter"
        [Runner] --> FileReader
    }

    component CLI {
        [CLI] --> Runner
    }
}

component AST {
    [AST] -> Token
}

"Lexer, Parser e Interpreter" -down-> Token
"Lexer, Parser e Interpreter" --> Providers
"Linter y Formatter" -down-> Token
"Linter y Formatter" --> FileReader
"Linter y Formatter" --> AST
"Linter y Formatter" --> Providers
Providers <-- "Runner y CLI"


' Organizar el layout
left to right direction
top to bottom direction

@enduml
