@startuml

component Token
component FileReader
component Providers

component AST {
    [AST] --> Token
}

component Parser {
    [Parser] --> Token
    [Parser] --> AST
    [Parser] --> Providers
}

component Lexer {
    [Lexer] --> Token
    [Lexer] --> Providers
}

component Formatter {
    [Formatter] --> Token
    [Formatter] --> AST
    [Formatter] --> FileReader
}

component Interpreter {
    [Interpreter] --> AST
    [Interpreter] --> Token
    [Interpreter] --> Providers
}

component Linter {
    [Linter] --> Token
    [Linter] --> AST
    [Linter] --> FileReader
}

component Runner {
    [Runner] --> Lexer
    [Runner] --> Parser
    [Runner] --> Interpreter
    [Runner] --> Formatter
    [Runner] --> Providers
    [Runner] --> Linter
}

component CLI {
    [CLI] --> Runner
    [CLI] --> Providers
}

left to right direction
top to bottom direction

@enduml